name: VPN Rotation on Push

on:
  push:
    branches:
      - main  # Runs only when pushing to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  vpn-rotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure Docker is Running
        run: |
          sudo systemctl restart docker || echo "Docker restart failed"
          sudo docker info || echo "Docker is not running!"

      - name: Run NordVPN Container
        env:
          NORDVPN_TOKEN: ${{ secrets.NORDVPN_TOKEN }}
        run: |
          docker run -d --name nordvpn --cap-add=NET_ADMIN --cap-add=NET_RAW \
            -e TOKEN=$NORDVPN_TOKEN \
            -e CONNECT=United_States \
            -e TECHNOLOGY=NordLynx \
            ghcr.io/bubuntux/nordvpn

      - name: Wait for VPN to Establish
        run: sleep 10  # Ensure the VPN has time to connect

      - name: Get Initial Public IP
        id: initial_ip
        run: |
          INITIAL_IP=$(docker exec nordvpn curl -s ifconfig.me)
          echo "Initial Public IP: $INITIAL_IP"
          echo "INITIAL_IP=$INITIAL_IP" >> $GITHUB_ENV

      - name: Rotate VPN (Switch Server)
        run: |
          docker exec nordvpn nordvpn disconnect
          sleep 5
          docker exec nordvpn nordvpn connect Germany

      - name: Wait for New VPN Connection
        run: sleep 10  # Give time for reconnection

      - name: Get New Public IP
        id: new_ip
        run: |
          NEW_IP=$(docker exec nordvpn curl -s ifconfig.me)
          echo "New Public IP: $NEW_IP"
          echo "NEW_IP=$NEW_IP" >> $GITHUB_ENV

      - name: Compare IPs
        run: |
          echo "✅ VPN Rotation Successful!"
          echo "🌍 Initial Public IP: $INITIAL_IP"
          echo "🌎 New Public IP: $NEW_IP"
          if [ "$INITIAL_IP" = "$NEW_IP" ]; then
            echo "❌ VPN Rotation Failed: IPs did not change."
            exit 1
          else
            echo "✅ VPN Rotation Confirmed: IP changed successfully!"
          fi