name: VPN Rotation on Push

on:
  push:
    branches:
      - main  # Runs only when pushing to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  vpn-rotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Docker Properly
        run: |
          curl -fsSL https://get.docker.com | sudo sh
          sudo systemctl enable --now docker

      - name: Run NordVPN Container
        env:
          NORDVPN_TOKEN: ${{ secrets.NORDVPN_TOKEN }}
        run: |
          docker run -d --name nordvpn --cap-add=NET_ADMIN --cap-add=NET_RAW \
            -e TOKEN=$NORDVPN_TOKEN \
            -e CONNECT=United_States \
            -e TECHNOLOGY=NordLynx \
            ghcr.io/bubuntux/nordvpn

      - name: Verify VPN Connection
        run: |
          sleep 10  # Wait for the VPN to establish
          docker exec nordvpn curl -s ifconfig.me