name: NordVPN Rotation on Push

on:
  push:
    branches:
      - main  # Runs only when pushing to main

  workflow_dispatch:  # Allows manual trigger

jobs:
  vpn-rotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NordVPN CLI (Direct Download)
        run: |
          wget -qO nordvpn.deb https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn_3.16.4-1_amd64.deb
          sudo apt install -y ./nordvpn.deb
          rm nordvpn.deb  # Clean up installation file

      - name: Login to NordVPN
        run: nordvpn login --token ${{ secrets.NORDVPN_TOKEN }}

      - name: Connect to VPN
        run: nordvpn connect

      - name: Confirm VPN Connection
        run: curl -s ifconfig.me  # Outputs current public IP

      - name: Rotate VPN (Change Server)
        run: |
          nordvpn disconnect
          sleep 5
          nordvpn connect France  # Change to a specific country

      - name: Confirm New VPN Connection
        run: curl -s ifconfig.me  # Outputs new public IP