name: NordVPN Rotation on Push

on:
  push:
    branches:
      - main  # Runs only when pushing to main
  workflow_dispatch:  # Allows manual trigger

jobs:
  vpn-rotation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NordVPN via Snap
        run: |
          sudo snap install nordvpn
          sudo snap start nordvpn  # Start the NordVPN service

      - name: Login to NordVPN
        run: nordvpn login --token ${{ secrets.NORDVPN_TOKEN }}

      - name: Connect to VPN (Initial Connection)
        run: nordvpn connect United_States

      - name: Confirm Initial VPN Connection (Check Public IP)
        run: curl -s ifconfig.me  # Outputs current public IP

      - name: Rotate VPN (Change Server Once)
        run: |
          nordvpn disconnect
          sleep 5
          nordvpn connect Germany  # Change to a new server

      - name: Confirm New VPN Connection (Check New IP)
        run: curl -s ifconfig.me  # Outputs new public IP